SELECT
    FIN.NUNOTA,
    FIN.NUFIN,
    FIN.DESDOBRAMENTO AS PARCELA,

    FIN.DTNEG,
    FIN.DTVENC,
    FIN.DHBAIXA,

    CAB.CODPROJ,
    PRJ.IDENTIFICACAO AS PROJETO,

    CAB.CODTIPOPER,
    TOP.DESCROPER,

    CAB.CODTIPVENDA,
    TPV.DESCRTIPVENDA AS TIPO_NEGOCIACAO,

    PAR.RAZAOSOCIAL AS PARCEIRO,
    PAR.CGC_CPF,

    FIN.VLRDESDOB AS VALOR_TITULO,
    NVL(FIN.VLRBAIXA, 0) AS VALOR_BAIXA,

    FIN.VLRDESDOB
    - NVL(FIN.VLRBAIXA, 0) AS SALDO_ABERTO,

    CASE
        WHEN FIN.DHBAIXA IS NOT NULL
            THEN 'PAGO'
        WHEN FIN.DTVENC < TRUNC(SYSDATE)
            THEN 'VENCIDO'
        ELSE 'EM ABERTO'
    END AS STATUS_TITULO,

    MBC.HISTORICO,
    MBC.VLRLANC,
    MBC.DTLANC,
    MBC.RECDESP,
    MBC.ORIGMOV,
    MBC.NUBCO

FROM TGFFIN FIN

INNER JOIN TGFCAB CAB
        ON CAB.NUNOTA = FIN.NUNOTA

LEFT JOIN TGFTOP TOP
       ON TOP.CODTIPOPER = CAB.CODTIPOPER
      AND TOP.DHALTER = CAB.DHTIPOPER

LEFT JOIN TGFTPV TPV
       ON TPV.CODTIPVENDA = CAB.CODTIPVENDA
      AND TPV.DHALTER = CAB.DHTIPVENDA

LEFT JOIN TCSPRJ PRJ
       ON PRJ.CODPROJ = CAB.CODPROJ

LEFT JOIN TGFPAR PAR
       ON PAR.CODPARC = FIN.CODPARC

LEFT JOIN TGFMBC MBC
       ON MBC.NUBCO = FIN.NUBCO

WHERE CAB.CODTIPOPER IN (
    1101,
    1164,
    1166
)
  AND CAB.CODPROJ = {{CODPROJ}}

/*FILTRO_DTNEG_INICIAL*/
/*FILTRO_DTNEG_FINAL*/
/*FILTRO_NUNOTA*/

ORDER BY
    FIN.NUNOTA,
    FIN.DTVENC,
    FIN.DESDOBRAMENTO